#!/bin/bash

# Data
desktop_atual="cosmic"

# BMN Setup
git clone https://github.com/MatheusNDDS/bmn-script.git
cd bmn-script
sudo bash bmn.sh -s

# Get BMN Powerfull tools
source /etc/bmn/init #(Sim... só para imprimir uns textos...)

# Instalar minhas tralhas
-out -hT Instalando o MD OS
-out -t O que significa ”MD“? 
-out -t E de onde tiro essas ””aspas”” lindas? 
-out -t Para isso falta, seguimos...
sudo bmn -v -i n-bash ${desktop_atual}-shell md-env

# Clean environment
mv ../bmn-script /tmp